/**
 * AUTO-GENERATED by scripts/syncDevAlphaOverlays.ts — do not edit manually.
 * Run: npm run refresh:dev-overlays
 */

import type { DevOverlayDef } from './devOverlayAssets'

export const GENERATED_DEV_ALPHA_BATCH_OVERLAYS: DevOverlayDef[] = [
  {
    id: 'alpha-acorus',
    label: 'Acorus',
    file: 'acorus.png',
    defaultWidth: 220,
    aspect: 1,
    group: 'alpha_batch' as const,
    cacheBust: '1782946162843',
  },
  {
    id: 'alpha-ajuga',
    label: 'Ajuga',
    file: 'ajuga.png',
    defaultWidth: 200,
    aspect: 1,
    group: 'alpha_batch' as const,
    cacheBust: '1782946162844',
  },
  {
    id: 'alpha-alstroemeria',
    label: 'Alstroemeria',
    file: 'alstroemeria.png',
    defaultWidth: 220,
    aspect: 1,
    group: 'alpha_batch' as const,
    cacheBust: '1782946162845',
  },
  {
    id: 'alpha-apodasmia',
    label: 'Apodasmia',
    file: 'apodasmia.png',
    defaultWidth: 220,
    aspect: 1,
    group: 'alpha_batch' as const,
    cacheBust: '1782946162846',
  },
  {
    id: 'alpha-astilbe',
    label: 'Astilbe',
    file: 'astilbe.png',
    defaultWidth: 220,
    aspect: 1,
    group: 'alpha_batch' as const,
    cacheBust: '1782946162849',
  },
  {
    id: 'alpha-azalea',
    label: 'Azalea',
    file: 'azalea.png',
    defaultWidth: 240,
    aspect: 1,
    group: 'alpha_batch' as const,
    cacheBust: '1782946162850',
  },
  {
    id: 'alpha-carex',
    label: 'Carex',
    file: 'carex.png',
    defaultWidth: 200,
    aspect: 1,
    group: 'alpha_batch' as const,
    cacheBust: '1782946162854',
  },
  {
    id: 'alpha-choisya',
    label: 'Choisya',
    file: 'choisya.png',
    defaultWidth: 240,
    aspect: 1,
    group: 'alpha_batch' as const,
    cacheBust: '1782946162856',
  },
  {
    id: 'alpha-clumping-bamboo',
    label: 'Clumping Bamboo',
    file: 'clumping-bamboo.png',
    defaultWidth: 280,
    aspect: 1,
    group: 'alpha_batch' as const,
    cacheBust: '1782946162859',
  }
]
