/**
 * AUTO-GENERATED by scripts/refreshDevOverlayManifest.ts — do not edit manually.
 * Run: npm run refresh:dev-overlays
 */

import type { DevOverlayDef } from './devOverlayAssets'

export const GENERATED_NEW_BATCH_TEST_OVERLAYS: DevOverlayDef[] = [
  {
    id: 'batch-akeake',
    label: 'Akeake',
    file: 'akeake.png',
    defaultWidth: 220,
    aspect: 1,
    group: 'latest_batch' as const,
    cacheBust: '1782726829880',
  },
  {
    id: 'batch-apple',
    label: 'Apple',
    file: 'apple.png',
    defaultWidth: 220,
    aspect: 1,
    group: 'latest_batch' as const,
    cacheBust: '1782726829881',
  },
  {
    id: 'batch-birds-of-paradise',
    label: 'Birds Of Paradise',
    file: 'birds-of-paradise.png',
    defaultWidth: 220,
    aspect: 1,
    group: 'latest_batch' as const,
    cacheBust: '1782726829882',
  },
  {
    id: 'batch-boxelder',
    label: 'Boxelder',
    file: 'boxelder.png',
    defaultWidth: 220,
    aspect: 1,
    group: 'latest_batch' as const,
    cacheBust: '1782726829883',
  },
  {
    id: 'batch-buxus-ball',
    label: 'Buxus Ball',
    file: 'buxus-ball.png',
    defaultWidth: 220,
    aspect: 1,
    group: 'latest_batch' as const,
    cacheBust: '1782726829885',
  },
  {
    id: 'batch-renga-renga',
    label: 'Renga Renga',
    file: 'renga-renga.png',
    defaultWidth: 220,
    aspect: 1,
    group: 'latest_batch' as const,
    cacheBust: '1782726829887',
  }
]
