-- Pocket Gardener: missing ornamental plants from Kings Plant Barn comparison
-- 35 plants (34 Kings gaps + Puka / Meryta sinclairii)
--
-- Safe / idempotent:
-- 1) Does NOT set plants.id — uses the table default (serial/identity) so the sequence stays in sync.
-- 2) Skips rows where common_name OR scientific_name already exists (case-insensitive).
-- 3) Plant rows only — no remedies (add separately if needed).
-- 4) No visualiser mappings here — wire overlays in app asset files.
-- 5) flower_color must match check_flower_color: White, Pink, Red, Blue, Yellow, Purple, Orange, None, or NULL.
-- 6) task_category must match plants_task_category_check:
--    Citrus, Climber, Deciduous, Evergreen, Flowering Shrub, Hedge, Palm, Perennial (or NULL).
--
-- After running, use the verification SELECT at the bottom.

BEGIN;

WITH new_plants (
  common_name, plant_type, scientific_name, evergreen, overview, pruning_care, maintenance_considerations, sun_requirement, soil_type, flower_color, pro_tip, is_native, is_common, description, hardiness_level, maintenance_level, image_url, is_star_performer, water_behavior, placement, mature_size, trim_cycle, feed_cycle, health_focus, maintenance_notes, trim_notes, feed_notes, health_notes, builder_image_url, task_category, slope_suitability, style_tags
) AS (
VALUES
  ('Agapanthus', 'Perennial', 'Agapanthus praecox', true, 'A tough strappy perennial commonly used in Auckland borders, driveways and mass plantings. It handles sun, wind and dry spells once established.', 'Remove spent flower stems after flowering and pull or cut off old yellow leaves at the base.', 'Low maintenance, but clumps can become congested over time. Divide every few years if flowering slows or the plant spreads too far.', ARRAY['Full Sun','Part Shade'], ARRAY['Clay','Healthy/loam','Sandy'], 'Blue / White', 'Great for difficult sunny spots, but avoid letting seed heads spread into native bush or waterways. Use sterile/dwarf cultivars where possible.', false, true, 'Agapanthus is a reliable evergreen flowering perennial with strappy foliage and blue or white summer flower heads. It is useful for edging, driveways, slopes and low-maintenance gardens.', 'Hardy', 'Low', NULL, true, ARRAY['Dry','Drains Well'], 'Borders, driveways, mass planting, slopes and coastal gardens.', ARRAY['<1m'], 'After flowering / tidy annually', 'Spring', 'Snails, crown rot and unwanted self-seeding.', 'Remove dead leaves and spent stems. Divide large clumps when crowded.', 'Cut flower stems to the base after flowering. Remove old leaves by hand or with secateurs.', 'Apply compost or slow-release fertiliser in spring if growth is weak.', 'Watch for snails hiding in dense foliage and avoid waterlogged crowns.', NULL, 'Perennial', ARRAY['flat','gentle','moderate'], ARRAY['Low Maintenance','Coastal','Formal']),
  ('Carex', 'Grass', 'Carex spp.', true, 'A versatile grass-like sedge used for texture, native-style planting, damp areas and low-maintenance borders.', 'Comb out dead foliage or cut back tired clumps in late winter to refresh growth.', 'Usually low maintenance. Some varieties prefer moisture while others tolerate drier positions once established.', ARRAY['Full Sun','Part Shade'], ARRAY['Clay','Healthy/loam','Sandy'], 'Brown', 'Carex is excellent for softening paths and retaining edges. Choose the variety to match the site, as some love moisture and others prefer free-draining soil.', true, true, 'Carex are grass-like sedges valued for fine foliage texture, movement and reliable performance in Auckland gardens. They work well in borders, rain gardens and native-style plantings.', 'Hardy', 'Low', NULL, true, ARRAY['Holds Water','Drains Well'], 'Mass planting, borders, rain gardens, banks and path edges.', ARRAY['<1m'], 'Late winter / as needed', 'Spring', 'Crown rot in wet compacted soil and browning older foliage.', 'Keep weeds out while establishing. Refresh tired clumps by cutting back or dividing.', 'Comb out dead leaves or cut back hard in late winter if the plant looks messy.', 'Apply a light slow-release fertiliser or compost in spring.', 'Avoid burying the crown with mulch. Improve drainage if plants collapse in winter.', NULL, 'Grass', ARRAY['flat','gentle','moderate'], ARRAY['Native','Low Maintenance','Coastal']),
  ('Cyclamen', 'Flower', 'Cyclamen spp.', false, 'A seasonal flowering plant for pots, shaded entries and winter colour. Best treated as a cool-season ornamental in Auckland.', 'Remove spent flowers and yellow leaves by twisting or cutting at the base.', 'Needs good drainage and gentle watering. Avoid wetting the crown and protect from harsh afternoon sun.', ARRAY['Part Shade','Full Shade'], ARRAY['Potting Mix','Well Drained'], 'Pink / White / Red', 'Cyclamen dislike sitting wet. Water the potting mix rather than the crown and keep them in bright shade for the longest display.', false, true, 'Cyclamen are compact seasonal ornamentals grown for bright flowers and patterned leaves. They are ideal for pots, patios and cool shaded garden spots.', 'Semi-Hardy', 'Medium', NULL, false, ARRAY['Drains Well','Under a Roof'], 'Pots, shaded patios, doorways and cool sheltered beds.', ARRAY['<1m'], 'Deadhead through flowering season', 'During flowering', 'Crown rot, aphids and overwatering.', 'Keep evenly moist but never waterlogged. Remove spent flowers and leaves promptly.', 'Twist off old flower stems and yellow leaves from the base.', 'Use a weak liquid fertiliser while flowering if in pots.', 'If stems collapse, check for overwatering or crown rot.', NULL, 'Seasonal Colour', ARRAY['flat'], ARRAY['Cottage','Pots','Shade']),
  ('Photinia', 'Hedge', 'Photinia x fraseri', true, 'A fast-growing evergreen hedge or screening shrub known for bright red new growth.', 'Trim lightly several times through the growing season to encourage dense red new shoots.', 'Needs airflow and reasonably fertile soil. Can suffer leaf spot in humid, crowded conditions.', ARRAY['Full Sun','Part Shade'], ARRAY['Clay','Healthy/loam','Well Drained'], 'White', 'Regular light trimming gives the best red flush. Avoid letting it get too woody before you start shaping the hedge.', false, true, 'Photinia is a popular screening and hedging plant with glossy evergreen leaves and red new growth. It is useful where fast privacy is needed.', 'Hardy', 'Medium', NULL, true, ARRAY['Drains Well'], 'Hedges, boundaries, screens and background shrubs.', ARRAY['2-4m','4m+'], 'Every 6-10 weeks in growing season', 'Spring and late summer', 'Leaf spot, poor airflow and drought stress while establishing.', 'Water well while establishing and mulch around the root zone.', 'Trim little and often to keep dense growth and bright red foliage.', 'Apply slow-release fertiliser in spring and again lightly in late summer.', 'Improve airflow and remove badly spotted leaves if leaf spot becomes an issue.', NULL, 'Hedge', ARRAY['flat','gentle'], ARRAY['Screening','Formal','Low Maintenance']),
  ('Daphne', 'Shrub', 'Daphne odora', true, 'A compact evergreen shrub grown for highly fragrant winter flowers.', 'Avoid hard pruning. Lightly tip prune after flowering only if needed.', 'Can be fussy. Needs excellent drainage, cool roots and minimal disturbance once planted.', ARRAY['Part Shade'], ARRAY['Healthy/loam','Well Drained'], 'Pink / White', 'Plant Daphne once and leave it alone. It dislikes root disturbance, wet feet and heavy pruning.', false, true, 'Daphne is a classic scented shrub for sheltered Auckland gardens, producing fragrant winter flowers and glossy evergreen foliage.', 'Semi-Hardy', 'Medium', NULL, false, ARRAY['Drains Well','Under a Roof'], 'Sheltered entrances, shaded borders, pots and fragrance gardens.', ARRAY['<1m','1-2m'], 'After flowering only if needed', 'Spring', 'Root rot, yellowing leaves and sudden dieback.', 'Keep roots cool with mulch but keep mulch away from the stem. Avoid moving once established.', 'Only remove dead tips or lightly shape after flowering.', 'Use a gentle acid-loving fertiliser or compost in spring.', 'If leaves yellow or branches die back, check drainage and avoid overwatering.', NULL, 'Flowering Shrub', ARRAY['flat','gentle'], ARRAY['Fragrant','Cottage','Shade']),
  ('Teucrium', 'Hedge', 'Teucrium fruticans', true, 'A tough silver-grey shrub used for clipped hedges, coastal gardens and dry sunny borders.', 'Clip regularly for a formal hedge or prune after flowering to keep compact.', 'Needs sun and drainage. Can get leggy if left untrimmed.', ARRAY['Full Sun'], ARRAY['Sandy','Healthy/loam','Well Drained'], 'Blue', 'Excellent Buxus alternative for hot, dry or coastal spots where a silver clipped hedge suits the design.', false, true, 'Teucrium is an evergreen Mediterranean shrub with silver foliage and small blue flowers. It responds well to clipping and suits dry Auckland gardens.', 'Hardy', 'Low', NULL, true, ARRAY['Dry','Drains Well'], 'Low hedges, coastal gardens, sunny borders and formal edging.', ARRAY['1-2m'], 'Every 8-12 weeks in growing season', 'Spring', 'Leggy growth and root rot in wet soil.', 'Keep in full sun and avoid heavy wet soils.', 'Clip regularly for density. Renovate gradually rather than cutting hard into old wood.', 'Light feed in spring only; avoid lush soft growth.', 'If foliage yellows or collapses, check drainage.', NULL, 'Hedge', ARRAY['flat','gentle'], ARRAY['Coastal','Formal','Low Maintenance']),
  ('Nandina', 'Shrub', 'Nandina domestica', true, 'A compact evergreen shrub with colourful foliage, often used in low-maintenance borders and mass planting.', 'Remove old canes at the base to refresh the plant rather than shearing the top.', 'Very easy care once established. Colour is strongest in sun.', ARRAY['Full Sun','Part Shade'], ARRAY['Clay','Healthy/loam','Well Drained'], 'White', 'For the best shape, thin old stems from the base instead of trimming across the top like a hedge.', false, true, 'Nandina is a reliable foliage shrub with red, bronze or lime-toned new growth depending on variety. It is useful in low hedges, borders and modern plantings.', 'Hardy', 'Low', NULL, true, ARRAY['Drains Well','Dry'], 'Borders, low hedges, mass planting, pots and entrance gardens.', ARRAY['<1m','1-2m'], 'Late winter / as needed', 'Spring', 'Scale, poor colour in too much shade and old woody stems.', 'Water while establishing. Remove old stems if the plant becomes congested.', 'Thin older canes from the base in late winter. Avoid heavy shearing.', 'Apply compost or slow-release fertiliser in spring.', 'Check dense stems for scale and improve airflow if needed.', NULL, 'Shrub', ARRAY['flat','gentle'], ARRAY['Low Maintenance','Formal','Modern']),
  ('Loropetalum', 'Shrub', 'Loropetalum chinense', true, 'A burgundy foliage shrub with fringe-like pink flowers, useful for colour contrast in borders.', 'Lightly trim after flowering to keep compact. Avoid heavy repeated shearing unless used as a hedge.', 'Best foliage colour in sun. Needs good drainage and benefits from mulch.', ARRAY['Full Sun','Part Shade'], ARRAY['Healthy/loam','Well Drained'], 'Pink', 'Use Loropetalum as a dark foliage contrast beside greens, silvers and lime-toned plants.', false, true, 'Loropetalum is an evergreen ornamental shrub with purple-burgundy foliage and pink fringe flowers. It suits Auckland borders, low hedges and feature planting.', 'Hardy', 'Low', NULL, true, ARRAY['Drains Well'], 'Feature shrubs, low hedges, mixed borders and colour contrast planting.', ARRAY['1-2m','2-4m'], 'After flowering / as needed', 'Spring', 'Poor colour in shade, mites and dry stress.', 'Mulch and water during dry establishment periods.', 'Lightly shape after flowering. Remove awkward stems to maintain a natural form.', 'Feed in spring with a balanced slow-release fertiliser.', 'If leaves bronze poorly, move or prune surrounding plants to improve light.', NULL, 'Flowering Shrub', ARRAY['flat','gentle'], ARRAY['Modern','Cottage','Colour Foliage']),
  ('Pieris', 'Shrub', 'Pieris japonica', true, 'A shade-tolerant evergreen shrub with colourful new growth and clusters of bell-shaped flowers.', 'Prune lightly after flowering if needed and remove damaged shoots.', 'Prefers acidic, humus-rich soil and consistent moisture. Avoid lime and harsh afternoon sun.', ARRAY['Part Shade'], ARRAY['Healthy/loam','Well Drained'], 'White / Pink', 'Treat Pieris like a small rhododendron: cool roots, acidic soil, mulch and no wet feet.', false, true, 'Pieris is an evergreen acid-loving shrub grown for spring flowers and colourful red or bronze new foliage. It suits sheltered part-shade gardens.', 'Semi-Hardy', 'Medium', NULL, false, ARRAY['Drains Well','Holds Water'], 'Part-shade borders, woodland gardens and sheltered entrances.', ARRAY['1-2m'], 'After flowering', 'Spring', 'Lacebug, yellowing leaves and root stress.', 'Mulch annually with compost or leaf mould and keep soil evenly moist.', 'Only lightly prune after flowering to shape.', 'Use acid-loving fertiliser in spring.', 'Yellow leaves may indicate alkaline soil, poor drainage or nutrient lock-up.', NULL, 'Flowering Shrub', ARRAY['flat','gentle'], ARRAY['Shade','Cottage','Woodland']),
  ('Azalea', 'Shrub', 'Rhododendron spp. (Azalea group)', true, 'A compact flowering shrub for part shade, widely used for spring colour in Auckland gardens.', 'Prune immediately after flowering if shaping is needed.', 'Needs acidic soil, cool roots and steady moisture. Avoid drying out in pots.', ARRAY['Part Shade'], ARRAY['Healthy/loam','Well Drained','Potting Mix'], 'Pink / White / Red', 'Add Azalea as its own searchable plant even though it sits under Rhododendron, because most homeowners search for Azalea by name.', false, true, 'Azaleas are compact rhododendrons grown for masses of spring flowers. They suit pots, shaded borders and underplanting in sheltered gardens.', 'Semi-Hardy', 'Medium', NULL, false, ARRAY['Drains Well','Holds Water'], 'Pots, shaded borders, under trees and entrance gardens.', ARRAY['<1m','1-2m'], 'After flowering', 'Late winter and spring', 'Lacebug, petal blight, dry roots and yellowing leaves.', 'Keep mulched and evenly moist, especially in pots.', 'Shape right after flowering so next season’s buds are not removed.', 'Use acid-loving fertiliser in late winter or early spring.', 'Check leaf undersides for lacebug if leaves look pale or speckled.', NULL, 'Flowering Shrub', ARRAY['flat','gentle'], ARRAY['Cottage','Shade','Pots']),
  ('Tibouchina', 'Shrub', 'Tibouchina spp.', true, 'A subtropical flowering shrub grown for rich purple flowers and lush foliage.', 'Prune after flowering or in spring to keep compact and encourage new flowering wood.', 'Best in warm, sheltered, frost-free Auckland positions. Protect from cold winds.', ARRAY['Full Sun','Part Shade'], ARRAY['Healthy/loam','Well Drained'], 'Purple', 'Give Tibouchina a warm wall, courtyard or sheltered corner and prune lightly after flowering to avoid it becoming leggy.', false, true, 'Tibouchina, or glory bush, is a showy subtropical shrub with vivid purple flowers. It suits warm Auckland gardens and sheltered feature planting.', 'Tender', 'Medium', NULL, false, ARRAY['Drains Well'], 'Sheltered borders, subtropical gardens, warm walls and feature planting.', ARRAY['1-2m','2-4m'], 'After flowering / spring', 'Spring and summer', 'Frost damage, leggy growth and mites.', 'Water during dry spells and mulch to keep roots cool.', 'Lightly prune after flowering or in spring to keep bushy.', 'Feed in spring and again in summer for flowering.', 'Protect from frost and check new growth for mites or aphids.', NULL, 'Flowering Shrub', ARRAY['flat','gentle'], ARRAY['Subtropical','Colour','Feature']),
  ('Choisya', 'Shrub', 'Choisya ternata', true, 'A fragrant evergreen shrub with glossy leaves and white citrus-scented flowers.', 'Trim after flowering to shape. Can be cut back moderately if it becomes leggy.', 'Easy care in sun or part shade with good drainage.', ARRAY['Full Sun','Part Shade'], ARRAY['Healthy/loam','Well Drained'], 'White', 'Good choice for a scented, tidy shrub near paths or entrances where you can enjoy the flowers.', false, true, 'Choisya, or Mexican orange blossom, is a reliable evergreen shrub with aromatic foliage and scented white flowers. It works well in mixed borders and informal hedges.', 'Hardy', 'Low', NULL, true, ARRAY['Drains Well'], 'Borders, informal hedges, entrances and scented gardens.', ARRAY['1-2m'], 'After flowering', 'Spring', 'Leggy growth and root stress in wet soil.', 'Mulch and water while establishing. Generally easy once settled.', 'Shape after flowering. Remove older stems if the shrub gets crowded.', 'Apply compost or slow-release fertiliser in spring.', 'Avoid heavy wet soil and check for scale in dense growth.', NULL, 'Flowering Shrub', ARRAY['flat','gentle'], ARRAY['Fragrant','Cottage','Low Maintenance']),
  ('Thuja', 'Hedge', 'Thuja occidentalis', true, 'A conifer used for formal screening, narrow hedging and vertical evergreen structure.', 'Trim lightly and regularly while actively growing. Avoid cutting hard into old brown wood.', 'Needs consistent moisture while establishing and good drainage. Browning can occur from drought, wet feet or over-pruning.', ARRAY['Full Sun','Part Shade'], ARRAY['Healthy/loam','Well Drained'], NULL, 'Never cut Thuja back past green foliage into old wood, as bare brown sections may not regrow.', false, true, 'Thuja is an evergreen conifer used for tidy screens, hedges and upright structure. It suits formal gardens where a dense green column or hedge is needed.', 'Hardy', 'Medium', NULL, false, ARRAY['Drains Well'], 'Formal hedges, screens, boundaries and vertical accents.', ARRAY['2-4m','4m+'], 'Light trim 2-3 times per year', 'Spring', 'Browning, spider mites, drought stress and poor drainage.', 'Water deeply while establishing and mulch the root zone.', 'Clip lightly only into green growth. Avoid hard renovation cuts.', 'Use a slow-release tree and shrub fertiliser in spring.', 'If browning appears, check soil moisture, drainage and mites before trimming harder.', NULL, 'Hedge', ARRAY['flat','gentle'], ARRAY['Formal','Screening','Evergreen']),
  ('Clumping Bamboo', 'Hedge', 'Bambusa spp.', true, 'A fast evergreen screening plant. Use clumping types only for easier garden management.', 'Remove old or weak culms at ground level and trim lower branches if a clean-stem look is wanted.', 'Clumping bamboo still expands over time and needs space. Running bamboo should be avoided or contained professionally.', ARRAY['Full Sun','Part Shade'], ARRAY['Healthy/loam','Clay','Well Drained'], NULL, 'For home gardens, choose clumping bamboo such as Bambusa gracilis and avoid running bamboo unless it is properly contained.', false, true, 'Clumping bamboo is used for quick privacy, vertical structure and tropical screening. It is best in warm, sheltered Auckland gardens with room to expand.', 'Hardy', 'Medium', NULL, false, ARRAY['Holds Water','Drains Well'], 'Privacy screens, tropical gardens and boundary planting with space.', ARRAY['2-4m','4m+'], 'Annual cane thinning / as needed', 'Spring and summer', 'Spread management, dry stress and wind scorch.', 'Water and feed during establishment. Allow enough width for the clump to mature.', 'Remove old culms at ground level. Trim sides carefully to maintain screen shape.', 'Feed in spring and summer with nitrogen-rich fertiliser or compost.', 'Dry rolled leaves usually indicate water stress or wind exposure.', NULL, 'Screening', ARRAY['flat','gentle'], ARRAY['Screening','Subtropical','Low Maintenance']),
  ('Grevillea', 'Shrub', 'Grevillea spp.', true, 'A bird-friendly evergreen shrub with fine foliage and nectar-rich flowers, often suited to dry sunny spots.', 'Tip prune after flowering to keep dense and remove old woody stems gradually.', 'Needs good drainage and low-phosphorus fertiliser. Avoid heavy feeding.', ARRAY['Full Sun'], ARRAY['Sandy','Well Drained'], 'Red / Pink / Orange', 'Use native/Australian low-phosphorus fertiliser only. Standard high-phosphorus fertilisers can damage Proteaceae plants.', false, true, 'Grevillea is a tough ornamental shrub grown for nectar flowers and fine-textured evergreen foliage. It suits sunny, free-draining Auckland gardens.', 'Hardy', 'Low', NULL, true, ARRAY['Dry','Drains Well'], 'Sunny borders, banks, bird-friendly gardens and dry coastal-style planting.', ARRAY['<1m','1-2m','2-4m'], 'After flowering', 'Spring with low-phosphorus fertiliser', 'Root rot, phosphorus sensitivity and leggy woody growth.', 'Plant in free-draining soil and avoid rich compost directly around roots.', 'Tip prune after flowering to maintain density.', 'Use low-phosphorus native fertiliser sparingly in spring.', 'Yellowing or collapse may come from wet soil or unsuitable fertiliser.', NULL, 'Shrub', ARRAY['flat','gentle','moderate'], ARRAY['Coastal','Bird Friendly','Low Maintenance']),
  ('Protea', 'Shrub', 'Protea spp.', true, 'A striking evergreen shrub grown for large architectural flowers and bold structure.', 'Prune lightly after flowering, cutting stems back to healthy leafy growth.', 'Requires excellent drainage, full sun and low-phosphorus feeding. Hates wet feet.', ARRAY['Full Sun'], ARRAY['Sandy','Well Drained'], 'Pink / Red / White', 'Proteas need drainage first. If your soil is heavy Auckland clay, build up a mound or raised bed before planting.', false, true, 'Proteas are dramatic flowering shrubs for sunny, free-draining gardens. They suit coastal and architectural planting where soil is not too rich or wet.', 'Semi-Hardy', 'Medium', NULL, false, ARRAY['Dry','Drains Well'], 'Sunny feature planting, coastal gardens, raised beds and cut-flower gardens.', ARRAY['1-2m','2-4m'], 'After flowering', 'Spring with low-phosphorus fertiliser', 'Root rot, phosphorus toxicity and poor flowering in shade.', 'Avoid disturbing roots and do not enrich the soil heavily.', 'Prune flowered stems back to leafy growth. Do not cut into bare old wood.', 'Use only low-phosphorus native/protea fertiliser.', 'Sudden collapse usually points to drainage or root disease.', NULL, 'Flowering Shrub', ARRAY['flat','gentle','moderate'], ARRAY['Coastal','Feature','Architectural']),
  ('Puka', 'Tree', 'Meryta sinclairii', true, 'A large NZ native evergreen tree with bold glossy leaves, suited to warm sheltered Auckland sites.', 'Remove dead or damaged leaves and lower branches if clearance is needed. Avoid heavy pruning unless shaping young trees.', 'Needs shelter from cold winds when young. Best in free-draining soil with room for a large crown.', ARRAY['Full Sun','Part Shade'], ARRAY['Healthy/loam','Well Drained','Sandy'], NULL, 'Give Puka space — it becomes a substantial architectural tree with very distinctive foliage.', true, true, 'Puka is a native evergreen tree grown for large leathery leaves and strong subtropical presence. It suits warm sheltered gardens and coastal-influenced Auckland sites.', 'Semi-Hardy', 'Low', NULL, false, ARRAY['Drains Well'], 'Feature trees, sheltered courtyards, subtropical and native gardens with space.', ARRAY['2-4m','4m+'], 'As needed / winter tidy', 'Spring', 'Wind damage, frost on young plants and root stress in wet clay.', 'Mulch and water while establishing. Protect from strong wind until the trunk toughens.', 'Remove damaged leaves and lower branches as needed. Avoid cutting the main leader unless required for clearance.', 'Light compost or slow-release fertiliser in spring during establishment.', 'Young plants may brown if exposed to frost or drying winds.', NULL, 'Evergreen', ARRAY['flat','gentle'], ARRAY['Native','Subtropical','Feature']),
  ('Leucadendron', 'Shrub', 'Leucadendron spp.', true, 'A colourful evergreen Proteaceae shrub grown for foliage bracts and strong landscape form.', 'Prune after flowering or after cutting stems to keep compact and encourage fresh growth.', 'Needs full sun, free drainage and low-phosphorus fertiliser.', ARRAY['Full Sun'], ARRAY['Sandy','Well Drained'], 'Yellow / Red / Pink', 'Regular picking or light pruning keeps Leucadendron bushy and prevents bare woody stems.', false, true, 'Leucadendrons provide year-round structure and colourful bracts in sunny, free-draining gardens. They are useful for coastal and modern landscape planting.', 'Semi-Hardy', 'Medium', NULL, true, ARRAY['Dry','Drains Well'], 'Sunny borders, coastal gardens, cut foliage and feature planting.', ARRAY['1-2m','2-4m'], 'After flowering / after cutting stems', 'Spring with low-phosphorus fertiliser', 'Root rot, phosphorus sensitivity and woody leggy growth.', 'Avoid rich wet soil and water regularly only while establishing.', 'Prune lightly after flowering, always leaving leafy growth below the cut.', 'Use low-phosphorus native/protea fertiliser in spring.', 'Check drainage if leaves yellow or plants suddenly wilt.', NULL, 'Shrub', ARRAY['flat','gentle','moderate'], ARRAY['Coastal','Modern','Architectural']),
  ('Leucospermum', 'Shrub', 'Leucospermum spp.', true, 'A showy evergreen shrub known as pincushion flower, grown for bright sculptural blooms.', 'Prune after flowering to maintain shape and remove spent flower stems.', 'Requires excellent drainage, full sun and low-phosphorus fertiliser.', ARRAY['Full Sun'], ARRAY['Sandy','Well Drained'], 'Orange / Yellow / Red', 'Leucospermum is less forgiving of wet soil than many shrubs. Raised planting is often the difference between success and failure in Auckland clay.', false, true, 'Leucospermum produces dramatic pincushion flowers on evergreen shrubs. It suits sunny, free-draining gardens and makes a strong feature plant.', 'Semi-Hardy', 'Medium', NULL, false, ARRAY['Dry','Drains Well'], 'Sunny feature beds, coastal gardens, raised beds and cut-flower gardens.', ARRAY['1-2m','2-4m'], 'After flowering', 'Spring with low-phosphorus fertiliser', 'Root rot, poor drainage and phosphorus sensitivity.', 'Plant high in free-draining soil and avoid heavy mulch against the stem.', 'Remove spent flowers and lightly shape after flowering.', 'Use low-phosphorus fertiliser only.', 'Wilting in wet soil is a serious warning sign; improve drainage quickly.', NULL, 'Flowering Shrub', ARRAY['flat','gentle','moderate'], ARRAY['Coastal','Feature','Architectural']),
  ('Salvia', 'Perennial', 'Salvia spp.', true, 'A long-flowering perennial or small shrub with colourful flower spikes loved by bees.', 'Deadhead through the season and cut back in late winter or early spring to refresh growth.', 'Most salvias prefer sun and drainage. Some can become woody without pruning.', ARRAY['Full Sun'], ARRAY['Healthy/loam','Sandy','Well Drained'], 'Purple / Blue / Pink / Red', 'Do not be afraid to cut shrubby salvias back in spring once frost risk has passed; they usually bounce back strongly.', false, true, 'Salvias are reliable flowering perennials for sunny borders, cottage gardens and pollinator planting. They offer long colour with relatively low care.', 'Hardy', 'Low', NULL, true, ARRAY['Dry','Drains Well'], 'Sunny borders, cottage gardens, pollinator gardens and pots.', ARRAY['<1m','1-2m'], 'Deadhead regularly; cut back late winter/spring', 'Spring and summer', 'Leggy growth, mildew and aphids.', 'Deadhead to keep flowers coming and keep plants open for airflow.', 'Cut back old stems in late winter or early spring. Lightly trim after flushes of flowers.', 'Feed lightly in spring and summer, especially in pots.', 'Improve airflow if mildew appears and avoid wetting foliage late in the day.', NULL, 'Perennial', ARRAY['flat','gentle'], ARRAY['Cottage','Pollinator','Low Maintenance']),
  ('Alstroemeria', 'Perennial', 'Alstroemeria spp.', true, 'A long-flowering clumping perennial grown for colourful flowers and good vase life.', 'Pull spent flowering stems from the base rather than cutting them if they release easily.', 'Likes fertile, free-draining soil and regular moisture while flowering.', ARRAY['Full Sun','Part Shade'], ARRAY['Healthy/loam','Well Drained'], 'Pink / Orange / White / Yellow', 'Harvest or remove stems by pulling from the base to encourage new shoots and more flowers.', false, true, 'Alstroemeria, or Peruvian lily, is a reliable flowering perennial for borders and cut flowers. It provides long seasonal colour in sunny or lightly shaded spots.', 'Hardy', 'Medium', NULL, true, ARRAY['Drains Well','Holds Water'], 'Borders, cutting gardens, cottage gardens and pots.', ARRAY['<1m'], 'Deadhead through flowering season', 'Spring and summer', 'Slugs, aphids and root rot in heavy wet soil.', 'Keep watered during dry flowering periods and mulch lightly.', 'Remove spent stems from the base to encourage repeat flowering.', 'Feed in spring and again during the flowering season.', 'Watch for slugs around new shoots.', NULL, 'Perennial', ARRAY['flat','gentle'], ARRAY['Cottage','Colour','Cut Flowers']),
  ('Hosta', 'Perennial', 'Hosta spp.', false, 'A shade perennial grown for lush decorative foliage.', 'Remove old leaves as they yellow or die down in winter.', 'Needs shade or morning sun, moisture and protection from slugs and snails.', ARRAY['Part Shade','Full Shade'], ARRAY['Healthy/loam','Clay'], 'Lavender / White', 'Slug control matters from the first spring shoots. Protect new growth before the damage is obvious.', false, true, 'Hostas are classic shade perennials with bold foliage in green, blue, lime or variegated forms. They suit pots and shaded borders.', 'Hardy', 'Medium', NULL, false, ARRAY['Holds Water'], 'Shade gardens, pots, woodland borders and underplanting.', ARRAY['<1m'], 'Tidy in winter', 'Spring', 'Slugs, snails, dry stress and leaf scorch.', 'Keep soil moist and mulch well. Divide clumps if they become crowded.', 'Remove damaged leaves and cut back old foliage after it dies down.', 'Apply compost or slow-release fertiliser in spring.', 'Use slug protection early in spring and avoid hot afternoon sun.', NULL, 'Perennial', ARRAY['flat','gentle'], ARRAY['Shade','Foliage','Pots']),
  ('Astilbe', 'Perennial', 'Astilbe spp.', false, 'A shade-loving perennial with ferny foliage and soft flower plumes.', 'Cut back old flower stems and remove dead foliage in winter.', 'Needs consistent moisture and rich soil. Struggles in hot dry positions.', ARRAY['Part Shade','Full Shade'], ARRAY['Healthy/loam','Clay'], 'Pink / White / Red', 'Astilbe is best where the soil stays cool and moist. Dry shade is usually too harsh without irrigation.', false, false, 'Astilbe adds soft flower plumes and fern-like foliage to shaded, moist borders. It is useful for woodland-style gardens and damp part-shade areas.', 'Hardy', 'Medium', NULL, false, ARRAY['Holds Water'], 'Moist shade borders, woodland gardens and near water features.', ARRAY['<1m'], 'After flowering / winter tidy', 'Spring', 'Dry stress, leaf scorch and poor flowering in dry shade.', 'Keep soil evenly moist and mulch annually.', 'Remove old flower stems and cut back dead foliage in winter.', 'Feed with compost or slow-release fertiliser in spring.', 'Brown crispy leaves usually mean the site is too dry or sunny.', NULL, 'Perennial', ARRAY['flat'], ARRAY['Shade','Cottage','Woodland']),
  ('Heuchera', 'Perennial', 'Heuchera spp.', true, 'A colourful foliage perennial for pots, borders and part shade.', 'Remove old or damaged leaves and spent flower stems as needed.', 'Needs drainage and protection from harsh afternoon sun. Can lift over time and may need replanting slightly deeper.', ARRAY['Part Shade'], ARRAY['Healthy/loam','Well Drained','Potting Mix'], 'White / Pink', 'Heuchera is mainly about foliage colour, so use it in groups near paths or pots where the leaves can be seen up close.', false, true, 'Heuchera, or coral bells, is grown for colourful evergreen foliage in burgundy, lime, caramel or silver tones. It suits pots and part-shade planting.', 'Hardy', 'Low', NULL, false, ARRAY['Drains Well'], 'Pots, shaded borders, edging and foliage contrast planting.', ARRAY['<1m'], 'Tidy as needed', 'Spring', 'Vine weevil, crown rot and leaf scorch.', 'Keep crowns above wet mulch and refresh plants if they become woody.', 'Remove tired leaves and spent flower stems at the base.', 'Light slow-release fertiliser in spring.', 'Check for root damage if the plant suddenly wilts despite moist soil.', NULL, 'Perennial', ARRAY['flat','gentle'], ARRAY['Foliage','Shade','Pots']),
  ('Ajuga', 'Groundcover', 'Ajuga reptans', true, 'A low spreading groundcover with coloured foliage and blue flower spikes.', 'Trim edges after flowering or when it spreads beyond the intended area.', 'Best in part shade with moisture. Can spread into lawns or soft edges if not contained.', ARRAY['Part Shade','Full Shade'], ARRAY['Clay','Healthy/loam'], 'Blue', 'Useful under shrubs where grass struggles, but edge it regularly so it does not creep into paths or lawns.', false, true, 'Ajuga, or carpet bugleweed, is a spreading evergreen groundcover for shaded borders and underplanting. It provides foliage colour and spring flowers.', 'Hardy', 'Low', NULL, false, ARRAY['Holds Water'], 'Underplanting, shaded edges, groundcover and between shrubs.', ARRAY['<1m'], 'After flowering / as needed', 'Spring', 'Slug damage, mildew and spread control.', 'Keep weeds out while establishing and edge runners as needed.', 'Trim back runners and spent flowers after flowering.', 'Apply compost or light fertiliser in spring if growth is weak.', 'Improve airflow if mildew appears in dense damp patches.', NULL, 'Groundcover', ARRAY['flat','gentle'], ARRAY['Shade','Groundcover','Low Maintenance']),
  ('Acorus', 'Grass', 'Acorus gramineus', true, 'A small grass-like perennial with tidy arching foliage, often used near water, pots and path edges.', 'Comb or cut out old foliage in late winter to refresh the clump.', 'Likes moisture but still needs oxygen around the roots. Avoid drying out in pots.', ARRAY['Full Sun','Part Shade'], ARRAY['Clay','Healthy/loam','Potting Mix'], NULL, 'Acorus is a good choice for damp edges where true dry-loving grasses struggle.', false, true, 'Acorus is a compact evergreen grass-like plant used for edging, damp borders and pots. Variegated and lime forms add bright foliage contrast.', 'Hardy', 'Low', NULL, false, ARRAY['Holds Water'], 'Damp borders, pond edges, pots, paths and small edging.', ARRAY['<1m'], 'Late winter / as needed', 'Spring', 'Dry tips, crown rot and pot drying.', 'Keep evenly moist and remove weeds around small clumps.', 'Comb out old foliage or cut back lightly in late winter.', 'Light feed in spring if needed.', 'Brown tips usually mean drying out or salt/wind exposure.', NULL, 'Grass', ARRAY['flat'], ARRAY['Foliage','Waterwise','Low Maintenance']),
  ('Libertia', 'Perennial', 'Libertia spp.', true, 'A native iris-like perennial with strappy foliage and small white flowers.', 'Remove old flower stems and pull out dead leaves from the base.', 'Tough once established and useful for native-style borders. Some varieties colour best in sun.', ARRAY['Full Sun','Part Shade'], ARRAY['Clay','Healthy/loam','Sandy'], 'White', 'Libertia gives a similar strappy effect to small flax but with finer texture and seasonal flowers.', true, true, 'Libertia, often called NZ iris, is a clumping native perennial with upright foliage and white flowers. It suits native gardens, borders and low-maintenance planting.', 'Hardy', 'Low', NULL, true, ARRAY['Drains Well','Dry'], 'Native borders, mass planting, edges and mixed perennial beds.', ARRAY['<1m'], 'Annual tidy', 'Spring', 'Rust, old foliage and overcrowding.', 'Remove old foliage and divide if clumps become congested.', 'Cut spent flower stems and pull dead leaves from the base.', 'Apply compost or light slow-release fertiliser in spring.', 'Improve airflow if rust spots appear on leaves.', NULL, 'Perennial', ARRAY['flat','gentle','moderate'], ARRAY['Native','Low Maintenance','Coastal']),
  ('Apodasmia', 'Grass', 'Apodasmia similis', true, 'A native rush-like plant useful for coastal, wet and naturalistic gardens.', 'Remove dead stems or cut back old clumps if they become messy.', 'Handles wet soils and coastal exposure, but still benefits from weed control while establishing.', ARRAY['Full Sun','Part Shade'], ARRAY['Clay','Sandy','Healthy/loam'], NULL, 'Excellent for rain gardens, swales and coastal planting where a fine upright native texture is needed.', true, true, 'Apodasmia similis, or oioi, is a native rush with fine upright stems. It is valuable for wet areas, coastal planting and native-style mass planting.', 'Hardy', 'Low', NULL, true, ARRAY['Holds Water','Drains Well'], 'Rain gardens, coastal gardens, swales, wet areas and native planting.', ARRAY['1-2m'], 'Annual tidy if needed', 'Spring', 'Weed competition and drying out during establishment.', 'Keep weed-free while young and water until established if planted in a dry site.', 'Remove dead stems or cut back untidy clumps in late winter.', 'Usually needs little feeding; compost in spring if growth is weak.', 'Poor growth is often from competition or being too dry before establishment.', NULL, 'Native Grass', ARRAY['flat','gentle'], ARRAY['Native','Coastal','Rain Garden']),
  ('Scleranthus', 'Groundcover', 'Scleranthus biflorus', true, 'A compact native cushion groundcover forming bright green mounds.', 'Very little pruning needed; trim only to remove dead or damaged patches.', 'Needs excellent drainage and low competition. Avoid heavy wet mulch over the cushion.', ARRAY['Full Sun','Part Shade'], ARRAY['Sandy','Well Drained'], NULL, 'Best treated like a living cushion for rock gardens and edges. Drainage is critical.', true, true, 'Scleranthus is a native cushion plant used as a fine-textured groundcover in rock gardens, edging and modern native planting.', 'Hardy', 'Medium', NULL, false, ARRAY['Drains Well'], 'Rock gardens, path edges, pots, mounds and native groundcover.', ARRAY['<1m'], 'Minimal / as needed', 'Spring', 'Rot, weed competition and drying out in pots.', 'Keep weeds away and avoid burying the plant with mulch.', 'Only trim out damaged patches if needed.', 'Use very light feeding in spring if growth is weak.', 'Brown patches often indicate poor drainage, drought stress or old congested growth.', NULL, 'Groundcover', ARRAY['flat','gentle'], ARRAY['Native','Modern','Groundcover']),
  ('Selliera', 'Groundcover', 'Selliera radicans', true, 'A low native groundcover that forms mats in damp or coastal conditions.', 'Trim edges as needed to keep within bounds.', 'Prefers moisture and can handle coastal conditions. Keep weed-free while establishing.', ARRAY['Full Sun','Part Shade'], ARRAY['Clay','Healthy/loam','Sandy'], 'White', 'A useful native lawn-alternative look for damp edges, but it needs less foot traffic than turf.', true, true, 'Selliera radicans is a creeping native groundcover with small green leaves and white flowers. It suits damp, coastal and naturalistic gardens.', 'Hardy', 'Low', NULL, false, ARRAY['Holds Water','Drains Well'], 'Native groundcover, damp edges, coastal gardens and between stepping stones with light traffic.', ARRAY['<1m'], 'As needed', 'Spring', 'Weeds, drying out and patchiness.', 'Water while establishing and keep weeds from overtaking low growth.', 'Trim edges if it spreads beyond the intended area.', 'Light compost or slow-release fertiliser in spring.', 'Patchy growth usually means inconsistent moisture or weed competition.', NULL, 'Groundcover', ARRAY['flat','gentle'], ARRAY['Native','Groundcover','Coastal']),
  ('Leptinella', 'Groundcover', 'Leptinella dioica', true, 'A low native mat-forming groundcover often called brass buttons.', 'Trim lightly or edge as needed.', 'Best with moisture and low competition. Can brown off if too dry or too hot.', ARRAY['Full Sun','Part Shade'], ARRAY['Healthy/loam','Clay'], 'Yellow', 'Use Leptinella between stones or as a small groundcover where it can stay cool and not be outcompeted.', true, true, 'Leptinella is a fine-textured native groundcover with ferny foliage and small button-like flowers. It suits damp edges, paths and native gardens.', 'Hardy', 'Medium', NULL, false, ARRAY['Holds Water'], 'Between pavers, damp groundcover, native gardens and path edges.', ARRAY['<1m'], 'As needed', 'Spring', 'Dry stress, weeds and patchy dieback.', 'Keep evenly moist while establishing and protect from aggressive weeds.', 'Edge or lightly trim to contain spread.', 'Apply light compost or slow-release fertiliser in spring.', 'Browning often comes from drying out, heat or poor establishment.', NULL, 'Groundcover', ARRAY['flat'], ARRAY['Native','Groundcover','Cottage']),
  ('Mandevilla', 'Climber', 'Mandevilla spp.', true, 'A warm-climate flowering climber or patio plant with glossy leaves and trumpet-shaped flowers.', 'Prune in spring to shape and train new growth onto support.', 'Needs warmth, shelter and good drainage. Often best in pots in cooler Auckland spots.', ARRAY['Full Sun','Part Shade'], ARRAY['Potting Mix','Well Drained'], 'Pink / Red / White', 'Give Mandevilla a warm sheltered wall or pot. It flowers best with heat and protection from cold wind.', false, true, 'Mandevilla is a showy flowering climber for warm sheltered gardens, patios and containers. It brings tropical colour through the warmer months.', 'Tender', 'Medium', NULL, false, ARRAY['Drains Well','Under a Roof'], 'Pots, warm patios, trellis, pergolas and sheltered walls.', ARRAY['1-2m','2-4m'], 'Spring / after flowering', 'Spring and summer', 'Cold damage, aphids, mites and dry pots.', 'Train onto support and keep watered during summer in pots.', 'Prune in spring to shape and remove cold-damaged growth.', 'Feed with flowering plant fertiliser through spring and summer.', 'Protect from frost and check new shoots for aphids.', NULL, 'Climber', ARRAY['flat'], ARRAY['Subtropical','Pots','Colour']),
  ('Jasmine', 'Climber', 'Jasminum spp.', true, 'A fragrant flowering climber or scrambling shrub. This is true jasmine, separate from Star Jasmine.', 'Prune after flowering to keep contained and remove tangled old growth.', 'Needs training and support. Can become tangled if not pruned regularly.', ARRAY['Full Sun','Part Shade'], ARRAY['Healthy/loam','Well Drained'], 'White / Yellow', 'Add separately from Star Jasmine because homeowners often search both, but Trachelospermum and Jasminum behave differently.', false, true, 'True jasmine is grown for scented flowers and climbing or scrambling growth. It suits trellis, fences and sheltered garden structures.', 'Semi-Hardy', 'Medium', NULL, false, ARRAY['Drains Well'], 'Trellis, fences, pergolas, arches and scented garden areas.', ARRAY['2-4m'], 'After flowering', 'Spring and summer', 'Tangled growth, aphids and poor flowering in shade.', 'Train young stems onto support and tie in as needed.', 'Prune after flowering to control size and remove old tangled stems.', 'Feed in spring and summer to support flowering.', 'If flowering is poor, check light levels and avoid overfeeding with nitrogen.', NULL, 'Climber', ARRAY['flat','gentle'], ARRAY['Fragrant','Climber','Cottage']),
  ('Potato Vine', 'Climber', 'Solanum jasminoides', true, 'A fast-growing evergreen climber with white or pale blue starry flowers.', 'Prune hard after flowering or in spring to control size and prevent tangling.', 'Vigorous and needs support. Can smother nearby plants if neglected.', ARRAY['Full Sun','Part Shade'], ARRAY['Healthy/loam','Well Drained'], 'White / Pale Blue', 'Useful for quick cover, but schedule pruning because it can become a tangled mass on fences and pergolas.', false, true, 'Potato vine is a vigorous flowering climber used to cover fences, trellis and pergolas. It provides quick evergreen cover in mild Auckland gardens.', 'Semi-Hardy', 'Medium', NULL, false, ARRAY['Drains Well'], 'Fences, pergolas, trellis and fast screening.', ARRAY['2-4m','4m+'], 'After flowering / spring', 'Spring', 'Overgrowth, aphids and frost damage.', 'Train early and keep away from small shrubs or trees it could smother.', 'Prune hard to control spread and remove tangled growth.', 'Light feed in spring if growth or flowering is weak.', 'Watch for aphids on soft new growth and trim frost-damaged tips in spring.', NULL, 'Climber', ARRAY['flat','gentle'], ARRAY['Climber','Screening','Cottage']),
  ('Plumbago', 'Shrub', 'Plumbago auriculata', true, 'A sprawling warm-climate shrub with clusters of soft blue flowers.', 'Cut back in spring to shape and remove frost-damaged or leggy growth.', 'Best in warm sunny sheltered spots. Can become sprawling without pruning.', ARRAY['Full Sun','Part Shade'], ARRAY['Healthy/loam','Well Drained'], 'Blue', 'Plumbago is great for soft blue colour over walls or banks, but it needs pruning if you want a tidy shape.', false, true, 'Plumbago is a warm-climate flowering shrub with sky-blue flowers and a relaxed spreading habit. It suits sunny banks, walls and informal borders.', 'Semi-Hardy', 'Medium', NULL, false, ARRAY['Dry','Drains Well'], 'Sunny banks, walls, informal hedges, warm borders and coastal gardens.', ARRAY['1-2m','2-4m'], 'Spring / after flowering', 'Spring and summer', 'Frost damage, sprawling growth and scale.', 'Water while establishing and mulch in exposed dry sites.', 'Cut back in spring to refresh and shape. Lightly trim after flowering if needed.', 'Feed in spring and summer for stronger flowering.', 'Check stems for scale and prune out frost-damaged growth in spring.', NULL, 'Flowering Shrub', ARRAY['flat','gentle','moderate'], ARRAY['Coastal','Cottage','Colour'])
),
inserted AS (
  INSERT INTO public.plants (
    created_at,
    common_name, plant_type, scientific_name, evergreen, overview, pruning_care, maintenance_considerations, sun_requirement, soil_type, flower_color, pro_tip, is_native, is_common, description, hardiness_level, maintenance_level, image_url, is_star_performer, water_behavior, placement, mature_size, trim_cycle, feed_cycle, health_focus, maintenance_notes, trim_notes, feed_notes, health_notes, builder_image_url, task_category, slope_suitability, style_tags
  )
  SELECT
    now() AS created_at,
    np.common_name, np.plant_type, np.scientific_name, np.evergreen, np.overview, np.pruning_care, np.maintenance_considerations, np.sun_requirement, np.soil_type,
    CASE
      WHEN np.flower_color IS NULL THEN NULL
      WHEN trim(split_part(np.flower_color, ' / ', 1)) = 'Brown' THEN 'None'
      WHEN trim(split_part(np.flower_color, ' / ', 1)) = 'Lavender' THEN 'Purple'
      WHEN trim(split_part(np.flower_color, ' / ', 1)) = 'Pale Blue' THEN 'Blue'
      WHEN trim(split_part(np.flower_color, ' / ', 1)) IN ('White', 'Pink', 'Red', 'Blue', 'Yellow', 'Purple', 'Orange', 'None')
        THEN trim(split_part(np.flower_color, ' / ', 1))
      ELSE 'None'
    END AS flower_color,
    np.pro_tip, np.is_native, np.is_common, np.description, np.hardiness_level, np.maintenance_level, np.image_url, np.is_star_performer, np.water_behavior,
    CASE WHEN np.placement IS NULL THEN NULL::text[] ELSE ARRAY[np.placement] END AS placement,
    np.mature_size, np.trim_cycle, np.feed_cycle, np.health_focus, np.maintenance_notes, np.trim_notes, np.feed_notes, np.health_notes, np.builder_image_url,
    CASE
      WHEN np.task_category IS NULL THEN NULL
      WHEN np.task_category IN ('Citrus', 'Climber', 'Deciduous', 'Evergreen', 'Flowering Shrub', 'Hedge', 'Palm', 'Perennial')
        THEN np.task_category
      WHEN np.task_category IN ('Shrub', 'Seasonal Colour') THEN 'Flowering Shrub'
      WHEN np.task_category = 'Screening' THEN 'Hedge'
      WHEN np.task_category IN ('Grass', 'Groundcover', 'Native Grass') THEN 'Perennial'
      ELSE 'Perennial'
    END AS task_category,
    np.slope_suitability, np.style_tags
  FROM new_plants np
  WHERE NOT EXISTS (
    SELECT 1
    FROM public.plants p
    WHERE lower(trim(p.common_name)) = lower(trim(np.common_name))
       OR (
         p.scientific_name IS NOT NULL
         AND np.scientific_name IS NOT NULL
         AND lower(trim(p.scientific_name)) = lower(trim(np.scientific_name))
       )
  )
  RETURNING id, common_name
)
SELECT count(*) AS rows_inserted FROM inserted;

-- Safety: if plants.id is backed by a sequence/identity, keep it aligned after any prior manual ids.
DO $$
DECLARE
  seq_name text;
BEGIN
  seq_name := pg_get_serial_sequence('public.plants', 'id');
  IF seq_name IS NOT NULL THEN
    PERFORM setval(
      seq_name,
      (SELECT COALESCE(MAX(id), 1) FROM public.plants),
      true
    );
  END IF;
END $$;

COMMIT;

-- ── Verification: all 35 target plants ───────────────────────────────────────
SELECT
  p.id,
  p.common_name,
  p.scientific_name,
  p.plant_type,
  p.is_native
FROM public.plants p
WHERE lower(trim(p.common_name)) IN (
  lower('Acorus'),
  lower('Agapanthus'),
  lower('Ajuga'),
  lower('Alstroemeria'),
  lower('Apodasmia'),
  lower('Astilbe'),
  lower('Azalea'),
  lower('Carex'),
  lower('Choisya'),
  lower('Clumping Bamboo'),
  lower('Cyclamen'),
  lower('Daphne'),
  lower('Grevillea'),
  lower('Heuchera'),
  lower('Hosta'),
  lower('Jasmine'),
  lower('Leptinella'),
  lower('Leucadendron'),
  lower('Leucospermum'),
  lower('Libertia'),
  lower('Loropetalum'),
  lower('Mandevilla'),
  lower('Nandina'),
  lower('Photinia'),
  lower('Pieris'),
  lower('Plumbago'),
  lower('Potato Vine'),
  lower('Protea'),
  lower('Puka'),
  lower('Salvia'),
  lower('Scleranthus'),
  lower('Selliera'),
  lower('Teucrium'),
  lower('Thuja'),
  lower('Tibouchina')
)
ORDER BY p.common_name;

-- Expect 35 rows. If fewer, compare against inserted names above and existing duplicates.
