/**
 * Regenerates devOverlayManifest.generated.ts from assets/plant-overlays/processed/.
 *
 * Discovers PNGs not already in the production registry or static dev QA list,
 * copies any missing files to public/plant-overlays/, and writes the "new batch"
 * entries consumed by /dev-overlay.
 *
 * Does not modify plantOverlayAssets.ts (production registry).
 */

import fs from 'fs'
import path from 'path'
import { REGISTERED_OVERLAY_PATHS } from '../src/lib/visualIdeas/plantOverlayAssets'
import { DEV_QA_OVERLAY_FILES } from '../src/lib/visualiser/devOverlayAssets'

const PROCESSED_DIR = path.resolve('assets/plant-overlays/processed')
const PUBLIC_DIR = path.resolve('public/plant-overlays')
const OUTPUT_FILE = path.resolve('src/lib/visualiser/devOverlayManifest.generated.ts')

function fileFromRegisteredPath(src: string): string {
  return src.replace(/^\/plant-overlays\//, '')
}

function slugify(filename: string): string {
  return path
    .basename(filename, path.extname(filename))
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, '-')
    .replace(/^-|-$/g, '')
}

function labelFromFilename(filename: string): string {
  const base = path.basename(filename, path.extname(filename))
  return base
    .replace(/[-_]+/g, ' ')
    .replace(/\s+/g, ' ')
    .trim()
    .replace(/\b\w/g, (c) => c.toUpperCase())
}

function escapeString(value: string): string {
  return value.replace(/\\/g, '\\\\').replace(/'/g, "\\'")
}

function main(): void {
  if (!fs.existsSync(PROCESSED_DIR)) {
    console.error(`Missing directory: ${PROCESSED_DIR}`)
    process.exit(1)
  }
  if (!fs.existsSync(PUBLIC_DIR)) {
    fs.mkdirSync(PUBLIC_DIR, { recursive: true })
  }

  const registeredFiles = new Set(
    REGISTERED_OVERLAY_PATHS.map(fileFromRegisteredPath),
  )
  const qaFiles = new Set(DEV_QA_OVERLAY_FILES)
  const knownFiles = new Set([...registeredFiles, ...qaFiles])

  const processedFiles = fs
    .readdirSync(PROCESSED_DIR)
    .filter((f) => {
      const ext = path.extname(f).toLowerCase()
      return ext === '.png' && !f.startsWith('.')
    })
    .sort((a, b) => a.localeCompare(b, undefined, { sensitivity: 'base' }))

  const newBatchFiles = processedFiles.filter((f) => !knownFiles.has(f))

  let copied = 0
  for (const file of newBatchFiles) {
    const src = path.join(PROCESSED_DIR, file)
    const dest = path.join(PUBLIC_DIR, file)
    if (!fs.existsSync(dest)) {
      fs.copyFileSync(src, dest)
      copied++
    }
  }

  const entries = newBatchFiles.map((file) => {
    const id = `batch-${slugify(file)}`
    const label = labelFromFilename(file)
    return `  {
    id: '${escapeString(id)}',
    label: '${escapeString(label)}',
    file: '${escapeString(file)}',
    defaultWidth: 220,
    aspect: 1,
    group: 'latest_batch' as const,
  }`
  })

  const content = `/**
 * AUTO-GENERATED by scripts/refreshDevOverlayManifest.ts — do not edit manually.
 * Run: npm run refresh:dev-overlays
 */

import type { DevOverlayDef } from './devOverlayAssets'

export const GENERATED_NEW_BATCH_TEST_OVERLAYS: DevOverlayDef[] = [
${entries.join(',\n')}
]
`

  fs.writeFileSync(OUTPUT_FILE, content, 'utf8')

  console.log(`Refreshed dev overlay manifest → ${path.relative(process.cwd(), OUTPUT_FILE)}`)
  console.log(`  Processed PNGs scanned:  ${processedFiles.length}`)
  console.log(`  Registered (skipped):    ${registeredFiles.size}`)
  console.log(`  Dev QA static (skipped): ${qaFiles.size}`)
  console.log(`  New batch entries:       ${newBatchFiles.length}`)
  if (copied > 0) {
    console.log(`  Copied to public/:       ${copied}`)
  }
  if (newBatchFiles.length > 0) {
    console.log('  New batch files:')
    for (const file of newBatchFiles) {
      console.log(`    · ${file}`)
    }
  }
  console.log('  Preview → http://localhost:3000/dev-overlay')
}

main()
