/**
 * Copies alpha-batch dev overlay PNGs to public/plant-overlays/ and regenerates
 * devAlphaBatchManifest.generated.ts. Skips Agapanthus (already in production).
 *
 * Run via: npm run refresh:dev-overlays
 */

import fs from 'fs'
import path from 'path'
import { DEV_ALPHA_BATCH_SPECS } from '../src/lib/visualiser/devAlphaBatchOverlays'

const PROCESSED_DIR = path.resolve('assets/plant-overlays/processed')
const RAW_DIR = path.resolve('assets/plant-overlays/raw')
const PUBLIC_DIR = path.resolve('public/plant-overlays')
const OUTPUT_FILE = path.resolve('src/lib/visualiser/devAlphaBatchManifest.generated.ts')

function escapeString(value: string): string {
  return value.replace(/\\/g, '\\\\').replace(/'/g, "\\'")
}

function findSourceFile(candidates: readonly string[]): { path: string; name: string } | null {
  for (const name of candidates) {
    for (const dir of [PROCESSED_DIR, RAW_DIR, PUBLIC_DIR]) {
      const filePath = path.join(dir, name)
      if (fs.existsSync(filePath)) {
        return { path: filePath, name }
      }
    }
  }
  return null
}

function cacheBustToken(filename: string): string {
  const filePath = path.join(PUBLIC_DIR, filename)
  if (fs.existsSync(filePath)) {
    return String(Math.floor(fs.statSync(filePath).mtimeMs))
  }
  return '0'
}

function statPair(a: string, b: string): number {
  return fs.statSync(a).mtimeMs - fs.statSync(b).mtimeMs
}

function noteAgapanthusComparison(): void {
  const processed = path.join(PROCESSED_DIR, 'agapanthus.png')
  const production = path.join(PUBLIC_DIR, 'agapanthus.png')
  if (!fs.existsSync(processed)) return

  console.log('  Agapanthus note: processed/agapanthus.png exists but is excluded from dev alpha picker (production asset unchanged).')
  if (fs.existsSync(production)) {
    const delta = statPair(processed, production)
    if (Math.abs(delta) < 1000) {
      console.log('    · Processed and production PNGs have similar timestamps — likely the same file.')
    } else if (delta > 0) {
      console.log('    · Processed PNG is newer than production — review on /dev-overlay (Production filter) before replacing.')
    } else {
      console.log('    · Production PNG is newer than processed source.')
    }
  }
}

export function syncDevAlphaOverlays(): void {
  if (!fs.existsSync(PUBLIC_DIR)) {
    fs.mkdirSync(PUBLIC_DIR, { recursive: true })
  }

  let copied = 0
  const missing: string[] = []
  const manifestEntries: string[] = []

  for (const spec of DEV_ALPHA_BATCH_SPECS) {
    const source = findSourceFile(spec.sourceCandidates)
    if (!source) {
      missing.push(`${spec.label} (${spec.file})`)
      console.warn(`  [dev-alpha] SKIP — no source PNG for ${spec.label}. Tried: ${spec.sourceCandidates.join(', ')}`)
      continue
    }

    const dest = path.join(PUBLIC_DIR, spec.file)
    fs.copyFileSync(source.path, dest)
    if (source.name !== spec.file) copied++

    const cacheBust = cacheBustToken(spec.file)
    manifestEntries.push(`  {
    id: 'alpha-${escapeString(spec.slug)}',
    label: '${escapeString(spec.label)}',
    file: '${escapeString(spec.file)}',
    defaultWidth: ${spec.defaultWidth},
    aspect: 1,
    group: 'alpha_batch' as const,
    cacheBust: '${cacheBust}',
  }`)
  }

  const content = `/**
 * AUTO-GENERATED by scripts/syncDevAlphaOverlays.ts — do not edit manually.
 * Run: npm run refresh:dev-overlays
 */

import type { DevOverlayDef } from './devOverlayAssets'

export const GENERATED_DEV_ALPHA_BATCH_OVERLAYS: DevOverlayDef[] = [
${manifestEntries.join(',\n')}
]
`

  fs.writeFileSync(OUTPUT_FILE, content, 'utf8')

  console.log(`Refreshed dev alpha batch → ${path.relative(process.cwd(), OUTPUT_FILE)}`)
  console.log(`  Alpha batch entries:     ${manifestEntries.length}`)
  if (copied > 0) console.log(`  Renamed/copied sources:  ${copied}`)
  if (missing.length > 0) {
    console.log(`  Missing sources:         ${missing.length}`)
    for (const item of missing) console.log(`    · ${item}`)
  }

  noteAgapanthusComparison()
}

if (require.main === module) {
  syncDevAlphaOverlays()
}
